version: '2'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: veipranges
       MYSQL_USER: laravel
       MYSQL_PASSWORD: laravel
  
   php:
     depends_on:
       - db
     image: php-laravel:latest
     volumes:
       - ./src:/var/www/html
     restart: always
   
   nginx:
     image: nginx:latest
     links:
        - php
     ports:
       - 8000:80
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
       - ./src:/var/www/html
       - ./logs/nginx-access.log:/var/log/nginx/access.log
       - ./logs/nginx-error.log:/var/log/nginx/error.log

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin:latest
     ports:
       - 9091:80
     restart: always

volumes:
    db_data:
